on: [push]

jobs:
  procursus:
    runs-on: macos-latest
    name: Installs Procursus
    steps:
      - name: Installs Procursus with GitHub action
        uses: beerpiss/procursus-action@main
      - name: Tests
        continue-on-error: true
        run: |
          echo "--- PATH ---"
          echo $PATH
          
          echo "--- CPATH ---"
          echo $CPATH
          
          echo "--- LIBRARY_PATH ---"
          echo $LIBRARY_PATH
          
          echo "--- apt ---"
          apt-get
  procursus-with-packages:
    runs-on: macos-latest
    name: Installs Procursus with extra packages
    steps:
      - name: Installs Procursus with GitHub action
        uses: beerpiss/procursus-action@main
        with:
          packages: cmake clang
      - name: Tests
        continue-on-error: true
        run: |
          echo "--- PATH ---"
          echo $PATH
          
          echo "--- CPATH ---"
          echo $CPATH
          
          echo "--- LIBRARY_PATH ---"
          echo $LIBRARY_PATH
          
          echo "--- apt ---"
          apt-get
  procursus-no-cache:
    runs-on: macos-latest
    name: Installs Procursus (no cache)
    steps:
      - name: Installs Procursus with GitHub action 
        uses: beerpiss/procursus-action@main
        with:
         cache: false
      - name: Tests
        continue-on-error: true
        run: |
          echo "--- PATH ---"
          echo $PATH
          
          echo "--- CPATH ---"
          echo $CPATH
          
          echo "--- LIBRARY_PATH ---"
          echo $LIBRARY_PATH
          
          echo "--- apt ---"
          apt-get
